<?php

/**
 * @file
 * Maneja la creación y despliegue de objetos webpage (url o playlist).
 */

/**
 * Implements hook_menu().
 */
function islandora_webpage_menu() {
  return array(
    'admin/islandora/webpage/config' => array(
      'title' => 'Webpage Solution Pack',
      'description' => 'Configure the Webpage Solution Pack.',
      'page callback' => 'drupal_get_form',
      'access arguments' => array('administer site configuration'),
      'page arguments' => array('islandora_webpage_admin'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_webpage_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_webpage' => array(
      //'file' => 'theme/theme.inc', //REVISAR -> ¿Es necesario?
      'template' => 'theme/islandora-webpage',
      'pattern' => 'islandora_webpage__',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_webpage_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_webpage');
  // Webpage Content Model.
  $webpage_content_model = $connection->repository->constructObject('islandora:sp-webpageCModel');
  $webpage_content_model->owner = 'fedoraAdmin';
  $webpage_content_model->label = 'Islandora Webpage Content Model';
  $webpage_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $webpage_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_webpage_ds_composite_model.xml", FALSE);
  $webpage_content_model->ingestDatastream($datastream);
  // Webpage Collection.
  $webpage_collection = $connection->repository->constructObject('islandora:webpage_collection');
  $webpage_collection->owner = 'fedoraAdmin';
  $webpage_collection->label = 'Webpage Collection';
  $webpage_collection->models = 'islandora:collectionCModel';
  $webpage_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream.
  $datastream = $webpage_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_webpage_collection_policy.xml", FALSE);
  $webpage_collection->ingestDatastream($datastream);
  // TN Datastream.
  $datastream = $webpage_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/webpage.png", FALSE);
  $webpage_collection->ingestDatastream($datastream);
  return array(
    'islandora_webpage' => array(
      'title' => 'Islandora webpage',
      'objects' => array(
        $webpage_content_model,
        $webpage_collection,
      ),
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_webpage_islandora_sp_webpageCModel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_webpage', array('islandora_object' => $object));
  return array('islandora_webpage' => $output);
}

/**
 * Implements hook_preprocess_theme().
 */
function islandora_webpage_preprocess_islandora_webpage(array &$variables) {
  drupal_add_js('misc/form.js');
  drupal_add_js('misc/collapse.js');
  $islandora_object = $variables['islandora_object'];
  $repository = $islandora_object->repository;
  module_load_include('inc', 'islandora', 'includes/datastream');
  module_load_include('inc', 'islandora', 'includes/utilities');
  module_load_include('inc', 'islandora', 'includes/metadata');

  // We should eventually remove the DC object and dc_array code as it only
  // exists to not break legacy implementations.
  try {
    if (isset($islandora_object['DC']) && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $islandora_object['DC'])) {
      $dc = $islandora_object['DC']->content;
      $dc_object = DublinCore::importFromXMLString($dc);
    }
  }
  catch (Exception $e) {
    drupal_set_message(t('Error retrieving object %s %t', array('%s' => $islandora_object->id, '%t' => $e->getMessage())), 'error', FALSE);
  }
  $variables['islandora_dublin_core'] = isset($dc_object) ? $dc_object : NULL;
  $variables['dc_array'] = isset($dc_object) ? $dc_object->asArray() : array();
  $variables['islandora_object_label'] = $islandora_object->label;
  $variables['theme_hook_suggestions'][] = 'islandora_webpage__' . str_replace(':', '_', $islandora_object->id);
  $variables['parent_collections'] = islandora_get_parents_from_rels_ext($islandora_object);
  $variables['metadata'] = islandora_retrieve_metadata_markup($islandora_object);
  $variables['description'] = islandora_retrieve_description_markup($islandora_object);

  // Start getting parameters for the player...
  $webpage_params = array(
    "pid" => $islandora_object->id,
  );
  // Thumbnail.
  if (isset($islandora_object['TN']) && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $islandora_object['TN'])) {
    $tn_url = url("islandora/object/{$islandora_object->id}/datastream/TN/view");
    $params = array(
      'title' => $islandora_object->label,
      'path' => $tn_url,
    );
    $variables['islandora_thumbnail_img'] = theme('image', $params);

    $webpage_params += array(
      'tn' => $tn_url,
    );
  }

  // Video player.
  if (isset($islandora_object['OBJ']) && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $islandora_object['OBJ'])) {
    $webpge_url = trim($islandora_object['OBJ']->content);
    $webpage_params += array(
      "url" => $webpge_url,
      "mime" => 'text/plain',
    );
  }

  module_load_include('inc', 'islandora', 'includes/solution_packs');
  $viewer = islandora_get_viewer($webpage_params, 'islandora_webpage_viewers', $islandora_object);

  if ($viewer) {
    $variables['islandora_content'] = $viewer;
  }
  elseif (isset($variables['islandora_thumbnail_img']) && isset($islandora_object['OBJ']) &&
    islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $islandora_object['OBJ'])) {

    $variables['islandora_content'] = l($variables['islandora_thumbnail_img'], $webpge_url, array('html' => TRUE));
  }
  elseif (isset($islandora_object['OBJ']) && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $islandora_object['OBJ'])) {
    $variables['islandora_content'] = l($islandora_object->label, $webpge_url);
  }
}

/**
 * Implements hook_islandora_content_model_forms_form_associations().
 */
function islandora_webpage_islandora_content_model_forms_form_associations() {
  return array(
    'islandora_webpage_mods_form' => array(
      'content_model' => 'islandora:sp-webpageCModel',
      'form_name' => 'Webpage MODS form', //Taken from Audio SP
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_webpage_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_webpage');
  return array(
    'Webpage MODS form' => array( //Taken from Audio SP
      'form_file' => "$module_path/xml/islandora_webpage_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_webpage_islandora_sp_webpagecmodel_islandora_ingest_steps() {
  return array(
    /*'islandora_webpage_img_upload' => array(
      'weight' => 11,
      'type' => 'form',
      'form_id' => 'islandora_webpage_img_upload_form',
      'module' => 'islandora_webpage',
      'file' => 'includes/webpage_upload.form.inc',
    ),*/
    'islandora_webpage_upload' => array(
      'weight' => 12,
      'type' => 'form',
      'form_id' => 'islandora_webpage_upload_form',
      'module' => 'islandora_webpage',
      'file' => 'includes/webpage_upload.form.inc',
    ),
  );
}

/**
 * Implements hook_islandora_CMODEL_PID_derivative().
 */
function islandora_webpage_islandora_sp_webpagecmodel_islandora_derivative() {
  $derivatives = array();
  //IMG
  $derivatives[] = array(
    'source_dsid' => 'IMG',
    'destination_dsid' => 'TN',
    'weight' => '11',
    'function' => array(
      'islandora_webpage_add_tn_derivative',
    ),
    'file' => drupal_get_path('module', 'islandora_webpage') . '/includes/webpage_upload.form.inc',
  );
  return $derivatives;
}
