<?php

drupal_set_time_limit(1200);

/**
 * 
 */
function inah_import_tesis_menu(){
	$items = array();
	$items['admin/islandora/inah_import/tesis_batch'] = array(
		'title' => t( 'Tesis batch import'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('inah_import_tesis_admin'),
		'file' => 'include/inah_import_tesis_admin.inc',	
		'access arguments' => array(true),
		'type' => MENU_LOCAL_TASK,
	  );
  return $items;
}

