<?php

/**
 * @file
 * Maneja la creación y despliegue de objetos disco (audio tracks y pdf del librito).
 */

drupal_set_time_limit(1200);

/**
 * Implements hook_menu().
 */
function islandora_disco_menu() {
  return array(
    'admin/islandora/disco/config' => array(
      'title' => 'Disco Solution Pack',
      'description' => 'Configure the Disco Solution Pack.',
      'page callback' => 'drupal_get_form',
      'access arguments' => array('administer site configuration'),
      'page arguments' => array('islandora_disco_admin'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
    /*'islandora/object/%islandora_object/pdf' => array(
      'title' => 'PDF',
      'type' => MENU_LOCAL_TASK,
      'page callback' => 'islandora_disco_pdf_view',
      'page arguments' => array(2),
      'access callback' => 'islandora_disco_access',
      'access arguments' => array(2),
    ),*/
  );
}

/**
 * Determines whether or not to show this modules tab.
 *
 * @global object $user
 *
 * @param FedoraObject $fedora_object
 * A FedoraObject.
 * 
 * @return bool
 * Whether the user has access or not.
 */
function islandora_disco_access($fedora_object) {
  //Si queremos que aparezca en todos los objetos que contienen un PDF
  if (isset($fedora_object['PDF']) && user_access('view fedora repository objects')) {
    return TRUE;
  }
  return FALSE;

  $access = user_access('view fedora repository objects');
  $object = islandora_object_load($fedora_object);
// $object->models checks all the content models associated with an object and
// returns them as an array. So here, we're just checking if islandora:sp_pdf
// is inside the array of models for this particular object.
  $is_cmodel = array_key_exists('islandora:sp-discoCModel', array_flip($object->models));
  if ($access && $is_cmodel) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Renders the PDF local menu task view.
 *
 * @param AbstractObject $object
 *   The cd object to fetch the tracks from.
 *
 * @return string
 *   The HTML repersentation of the given cds tracks.
 */
function islandora_disco_pdf_view(AbstractObject $object) {
  // Create a form array.
  $output = array();
  // Create the fieldset title for the array.
  $output['title'] = array(
    '#type' => 'fieldset',
    '#title' => t('PDF Viewer'),
    '#collapsible' => FALSE,
  );
  $dsid = 'PDF';
  // Load the object we want.
  $object = islandora_object_load($object);
  // Check if the object has the specified datastream.
  if (isset($object[$dsid])) {
    $output['title']['description'] = array(
      '#markup' => theme('islandora_pdf', array('islandora_object' => $object)),
    );
  }
  // If there is no specified datastream, put that in the description instead.
  else {
    $output['title']['description'] = array(
      '#markup' => "No $dsid metadata was found for this object.",
    );
  }
  // Finally, return the form array to hook_menu.
  return $output;
}

/**
 * Implements hook_theme().
 */
function islandora_disco_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_disco' => array(
      //'file' => 'theme/theme.inc', //REVISAR -> ¿Es necesario?
      'template' => 'theme/islandora-disco',
      'pattern' => 'islandora_disco__',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_disco_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_disco');
  // Disco Content Model.
  $disco_content_model = $connection->repository->constructObject('islandora:sp-discoCModel');
  $disco_content_model->owner = 'fedoraAdmin';
  $disco_content_model->label = 'Islandora Disco Content Model';
  $disco_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $disco_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_disco_ds_composite_model.xml", FALSE);
  $disco_content_model->ingestDatastream($datastream);
  // Disco Collection.
  $disco_collection = $connection->repository->constructObject('islandora:disco_collection');
  $disco_collection->owner = 'fedoraAdmin';
  $disco_collection->label = 'Disco Collection';
  $disco_collection->models = 'islandora:collectionCModel';
  $disco_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream.
  $datastream = $disco_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_disco_collection_policy.xml", FALSE);
  $disco_collection->ingestDatastream($datastream);
  // TN Datastream.
  $datastream = $disco_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/disco.png", FALSE);
  $disco_collection->ingestDatastream($datastream);
  return array(
    'islandora_disco' => array(
      'title' => 'Islandora disco',
      'objects' => array(
        $disco_content_model,
        $disco_collection,
      ),
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_disco_islandora_sp_discoCModel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_disco', array('islandora_object' => $object));
  /*module_load_include('inc', 'islandora_inah_tabs', 'include/utilities');
  $output .= pintarTabs($object);*/
  return array('islandora_disco' => $output);
}

/**
 * Implements hook_preprocess_theme().
 */
function islandora_disco_preprocess_islandora_disco(array &$variables) {
  drupal_add_js('misc/form.js');
  drupal_add_js('misc/collapse.js');
  $islandora_object = $variables['islandora_object'];
  $repository = $islandora_object->repository;
  module_load_include('inc', 'islandora', 'includes/datastream');
  module_load_include('inc', 'islandora', 'includes/utilities');
  module_load_include('inc', 'islandora', 'includes/metadata');

  // We should eventually remove the DC object and dc_array code as it only
  // exists to not break legacy implementations.
  try {
    if (isset($islandora_object['DC']) && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $islandora_object['DC'])) {
      $dc = $islandora_object['DC']->content;
      $dc_object = DublinCore::importFromXMLString($dc);
    }
  }
  catch (Exception $e) {
    drupal_set_message(t('Error retrieving object %s %t', array('%s' => $islandora_object->id, '%t' => $e->getMessage())), 'error', FALSE);
  }
  $variables['islandora_dublin_core'] = isset($dc_object) ? $dc_object : NULL;
  $variables['dc_array'] = isset($dc_object) ? $dc_object->asArray() : array();
  $variables['islandora_object_label'] = $islandora_object->label;
  $variables['theme_hook_suggestions'][] = 'islandora_disco__' . str_replace(':', '_', $islandora_object->id);
  $variables['parent_collections'] = islandora_get_parents_from_rels_ext($islandora_object);
  $variables['metadata'] = islandora_retrieve_metadata_markup($islandora_object);
  $variables['description'] = islandora_retrieve_description_markup($islandora_object);

  // Start getting parameters for the player...
  $disco_params = array(
    "pid" => $islandora_object->id,
  );
  // Thumbnail.
  if (isset($islandora_object['TN']) && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $islandora_object['TN'])) {
    $tn_url = url("islandora/object/{$islandora_object->id}/datastream/TN/view");
    $params = array(
      'title' => $islandora_object->label,
      'path' => $tn_url,
    );
    $variables['islandora_thumbnail_img'] = theme('image', $params);

    $disco_params += array(
      'tn' => $tn_url,
    );
  }

  // Audio player.
  if (isset($islandora_object['PLAYLIST']) && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $islandora_object['PLAYLIST'])) {
    $playlist_url = url("islandora/object/{$islandora_object->id}/datastream/PLAYLIST", array('absolute' => TRUE));
    $disco_params += array(
      "url" => $playlist_url,
      "mime" => 'application/rss+xml',
      "listbarsize" => '50%',
    );
  }

  module_load_include('inc', 'islandora', 'includes/solution_packs');
  $viewer = islandora_get_viewer($disco_params, 'islandora_disco_viewers_audio', $islandora_object);

  if ($viewer) {
    $variables['islandora_content'] = $viewer;
  }
  elseif (isset($variables['islandora_thumbnail_img']) && isset($islandora_object['PLAYLIST']) &&
    islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $islandora_object['PLAYLIST'])) {

    $variables['islandora_content'] = l($variables['islandora_thumbnail_img'], $playlist_url, array('html' => TRUE));
  }
  elseif (isset($islandora_object['PLAYLIST']) && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $islandora_object['PLAYLIST'])) {
    $variables['islandora_content'] = l($islandora_object->label, $playlist_url);
  }
}

/**
 * Implements hook_islandora_content_model_forms_form_associations().
 */
function islandora_disco_islandora_content_model_forms_form_associations() {
  return array(
    'islandora_disco_mods_form' => array(
      'content_model' => 'islandora:sp-discoCModel',
      'form_name' => 'Disco MODS form', //Taken from Audio SP
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_disco_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_disco');
  return array(
    'Disco MODS form' => array( //Taken from Audio SP
      'form_file' => "$module_path/xml/islandora_disco_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_disco_islandora_sp_discocmodel_islandora_ingest_steps() {
  return array(
    'islandora_disco_pdf_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_disco_pdf_upload_form',
      'module' => 'islandora_disco',
      'file' => 'includes/disco_upload.form.inc',
    ),
    'islandora_disco_img_upload' => array(
      'weight' => 11,
      'type' => 'form',
      'form_id' => 'islandora_disco_img_upload_form',
      'module' => 'islandora_disco',
      'file' => 'includes/disco_upload.form.inc',
    ),
    'islandora_disco_audios_upload' => array(
      'weight' => 12,
      'type' => 'form',
      'form_id' => 'islandora_disco_audios_upload_form',
      'module' => 'islandora_disco',
      'file' => 'includes/disco_upload.form.inc',
    ),
  );
}

/**
 * Implements hook_islandora_CMODEL_PID_derivative() for the track object.
 */
/*function islandora_disco_islandora_track_discocmodel_islandora_derivative() {
  $derivatives = array();

  $derivatives[] = array(
    'source_dsid' => 'OBJ', //Audio
    'destination_dsid' => 'PROXY_MP3',
    'weight' => '0',
    'function' => array(
      'islandora_disco_create_mp3',
    ),
    'file' => drupal_get_path('module', 'islandora_disco') . '/includes/derivatives.inc',
  );

  $derivatives[] = array(
    'source_dsid' => 'OBJ', //Audio
    'destination_dsid' => 'PROXY_OGG',
    'weight' => '1',
    'function' => array(
      'islandora_disco_create_ogg',
    ),
    'file' => drupal_get_path('module', 'islandora_disco') . '/includes/derivatives.inc',
  );
  return $derivatives;
}*/

/**
 * Implements hook_islandora_CMODEL_PID_derivative().
 */
function islandora_disco_islandora_sp_discocmodel_islandora_derivative() {
  $derivatives = array();

  //PLAYLIST->No es necesario?
  /*$derivatives[] = array(
    'source_dsid' => 'NULL, //MP3 of child
    'destination_dsid' => 'playlist',
    'weight' => '2',
    'function' => array(
      'islandora_disco_create_playlist',
    ),
    'file' => drupal_get_path('module', 'islandora_disco') . '/includes/derivatives.inc',
  );*/

  //Este derivative puede ser agregado si queremos capturar el IMG desde la primera página del PDF
  //Se puede agregar la opción.
  /*
  $derivatives[] = array(
    'source_dsid' => 'PDF',
    'destination_dsid' => 'IMG',
    'weight' => '10',
    'function' => array(
      'islandora_disco_add_img_derivative',
    ),
    'file' => drupal_get_path('module', 'islandora_disco') . '/includes/derivatives.inc',
  );
  */
  //IMG
  $derivatives[] = array(
    'source_dsid' => 'IMG',
    'destination_dsid' => 'TN',
    'weight' => '11',
    'function' => array(
      'islandora_disco_add_tn_derivative',
    ),
    'file' => drupal_get_path('module', 'islandora_disco') . '/includes/derivatives.inc',
  );
  //FULL
  $derivatives[] = array(
    'source_dsid' => 'PDF',
    'destination_dsid' => 'FULL_TEXT',
    'weight' => '12',
    'function' => array(
      'islandora_disco_add_fulltext_derivative',
    ),
    'file' => drupal_get_path('module', 'islandora_disco') . '/includes/derivatives.inc',
  );
  return $derivatives;
}
