<?php

drupal_set_time_limit(1200);

/**
 * 
 */
function inah_import_youtube_menu(){
	$items = array();
	$items['admin/islandora/inah_import/youtube_batch'] = array(
		'title' => t( 'Youtube batch import'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('inah_import_youtube_admin'),
		'file' => 'include/inah_import_youtube_admin.inc',	
		'access arguments' => array(true),
		'type' => MENU_LOCAL_TASK,
	  );
  return $items;
}

